server {
    listen 80;
    server_name intproj23.sit.kmutt.ac.th;

   # return 301 https://$host/$request_uri;
    location /nw3/ {
        proxy_pass http://frontend:80/ ;  # Forward all other requests to frontend
        #return 301 https://$host/$request_uri;
    }
    #location /api/ {
     #   proxy_pass  http://backend:8080/;
    #}
}

server {
    listen 443 ssl;
    server_name intproj23.sit.kmutt.ac.th;

    ssl_certificate /etc/ssl/certs/fullchain.pem;
    ssl_certificate_key /etc/ssl/private/privkey.pem;
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout 5m;
    ssl_dhparam /etc/ssl/certs/dhparam-2048.pem;

    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'HIGH:!aNULL:!MD5';


#Publicte Pathนส่งไป backend)
    location / {
        proxy_pass  http://frontend:80/;
    }
    location /api/ {
        proxy_pass  http://backend:8080/;
    }
}
